apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autosnipe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: autosnipe-service
            port:
              number: 80
  tls:
  - hosts:
    - api.yourdomain.com
    secretName: your-tls-secret
