version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo/autosnipe
      - JWT_SECRET=your_very_strong_jwt_secret
      - ENCRYPTION_KEY=your_very_strong_encryption_key
      - ALLOWED_ORIGINS=https://yourdomain.com,https://anotherdomain.com
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: autosnipe
